// <auto-generated />
using System;
using GBM.psqlDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace pSQL_GBM.Migrations
{
    [DbContext(typeof(psqlContext))]
    [Migration("20230328143836_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gbm")
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GBM.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)")
                        .HasAnnotation("DataType", "nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SaltAndHashString")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users", "gbm");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GBM.User.Admin", b =>
                {
                    b.HasBaseType("GBM.User.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("GBM.User.Customer", b =>
                {
                    b.HasBaseType("GBM.User.User");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("GBM.User.Service", b =>
                {
                    b.HasBaseType("GBM.User.User");

                    b.HasDiscriminator().HasValue("Service");
                });

            modelBuilder.Entity("GBM.User.Staff", b =>
                {
                    b.HasBaseType("GBM.User.User");

                    b.HasDiscriminator().HasValue("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
